// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF5FrUaNDz31uT7FNxKy6pXZTU76A0RUE',
    appId: '1:589823919242:web:41e2c6956590814f101973',
    messagingSenderId: '589823919242',
    projectId: 'guardianai-d891d',
    authDomain: 'guardianai-d891d.firebaseapp.com',
    databaseURL: 'https://guardianai-d891d-default-rtdb.firebaseio.com',
    storageBucket: 'guardianai-d891d.firebasestorage.app',
    measurementId: 'G-1CGVP303W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYv0VPQ4Rg6XPBhiVVSSL6myggD9vsMEE',
    appId: '1:589823919242:android:48ff95f8093229fb101973',
    messagingSenderId: '589823919242',
    projectId: 'guardianai-d891d',
    databaseURL: 'https://guardianai-d891d-default-rtdb.firebaseio.com',
    storageBucket: 'guardianai-d891d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA65eLswbe80gnwVO9C1ryR78_1DznP-rI',
    appId: '1:589823919242:ios:d60fbed6eedc1c94101973',
    messagingSenderId: '589823919242',
    projectId: 'guardianai-d891d',
    databaseURL: 'https://guardianai-d891d-default-rtdb.firebaseio.com',
    storageBucket: 'guardianai-d891d.firebasestorage.app',
    androidClientId: '589823919242-ucdq3eagjcc8kueehpdhtlvum32chth0.apps.googleusercontent.com',
    iosClientId: '589823919242-0ejefloti85ag42p7v4ikdpkd8ur0i2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentriq',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA65eLswbe80gnwVO9C1ryR78_1DznP-rI',
    appId: '1:589823919242:ios:d60fbed6eedc1c94101973',
    messagingSenderId: '589823919242',
    projectId: 'guardianai-d891d',
    databaseURL: 'https://guardianai-d891d-default-rtdb.firebaseio.com',
    storageBucket: 'guardianai-d891d.firebasestorage.app',
    androidClientId: '589823919242-ucdq3eagjcc8kueehpdhtlvum32chth0.apps.googleusercontent.com',
    iosClientId: '589823919242-0ejefloti85ag42p7v4ikdpkd8ur0i2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentriq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF5FrUaNDz31uT7FNxKy6pXZTU76A0RUE',
    appId: '1:589823919242:web:53658e3ab3d57476101973',
    messagingSenderId: '589823919242',
    projectId: 'guardianai-d891d',
    authDomain: 'guardianai-d891d.firebaseapp.com',
    databaseURL: 'https://guardianai-d891d-default-rtdb.firebaseio.com',
    storageBucket: 'guardianai-d891d.firebasestorage.app',
    measurementId: 'G-848ER8VJM9',
  );
}
